#!/bin/bash
# Docker initialization script for DSSAT environment
# Ensures run_dssat utility is available in the expected location

set -e

# Define paths
DSSAT_DATA_DIR="/data"
UTILITIES_DIR="${DSSAT_DATA_DIR}/dssat-csm-os-develop/Utilities"
DSSAT_EXECUTABLE="/app/dssat/dscsm048"

echo "Initializing DSSAT environment..."

# Create the utilities directory structure
echo "Creating utilities directory: ${UTILITIES_DIR}"
mkdir -p "${UTILITIES_DIR}"

# Create the run_dssat script
echo "Creating run_dssat utility script..."
cat > "${UTILITIES_DIR}/run_dssat" << 'SCRIPT'
#!/bin/bash
# DSSAT runner script
# Auto-generated by Docker init script

# Check if DSSAT executable exists
if [ ! -f "/app/dssat/dscsm048" ]; then
    echo "Error: DSSAT executable not found at /app/dssat/dscsm048"
    exit 1
fi

# Run DSSAT with all provided arguments
exec /app/dssat/dscsm048 "$@"
SCRIPT

# Make the script executable
chmod +x "${UTILITIES_DIR}/run_dssat"

# Create backup locations for compatibility
echo "Creating backup utility locations..."
mkdir -p "/data/dssat-csm-data-develop/Utilities" 2>/dev/null || true
ln -sf "${UTILITIES_DIR}/run_dssat" "/data/dssat-csm-data-develop/Utilities/run_dssat" 2>/dev/null || true

# Create symlink in standard location
echo "Creating system symlink..."
mkdir -p /usr/local 2>/dev/null || true
ln -sf "${DSSAT_EXECUTABLE}" /usr/local/dscsm048 2>/dev/null || true

# Verify the script was created successfully
if [ -f "${UTILITIES_DIR}/run_dssat" ] && [ -x "${UTILITIES_DIR}/run_dssat" ]; then
    echo "✓ run_dssat utility created successfully at: ${UTILITIES_DIR}/run_dssat"
else
    echo "✗ Failed to create run_dssat utility"
    exit 1
fi

# Activate Python virtual environment if it exists
if [ -d "/app/venv" ]; then
    echo "Activating Python virtual environment..."
    source /app/venv/bin/activate
fi

echo "DSSAT environment initialized successfully!"
echo "Available utilities:"
echo "  - DSSAT executable: ${DSSAT_EXECUTABLE}"
echo "  - run_dssat script: ${UTILITIES_DIR}/run_dssat"

# Execute the provided command
exec "$@"